//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNM_CHITFUND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Enroll_Cust
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Enroll_Cust()
        {
            this.tbl_LiftedCustomer = new HashSet<tbl_LiftedCustomer>();
            this.tbl_MonthlyPayment = new HashSet<tbl_MonthlyPayment>();
        }
    
        public int Enroll_ID { get; set; }
        public string Cust_ID { get; set; }
        public string Chitt_ID { get; set; }
        public string IsLifted { get; set; }
    
        public virtual tbl_Chitti tbl_Chitti { get; set; }
        public virtual tbl_Cust tbl_Cust { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LiftedCustomer> tbl_LiftedCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MonthlyPayment> tbl_MonthlyPayment { get; set; }
    }
}
