//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNM_CHITFUND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Cust
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Cust()
        {
            this.tbl_Enroll_Cust = new HashSet<tbl_Enroll_Cust>();
            this.tbl_LiftedCustomer = new HashSet<tbl_LiftedCustomer>();
            this.tbl_MonthlyPayment = new HashSet<tbl_MonthlyPayment>();
        }
    
        public int ID { get; set; }
        public string Cust_ID { get; set; }
        public string Cust_Name { get; set; }
        public string Cust_Surname { get; set; }
        public string Cust_Father { get; set; }
        public string Gender { get; set; }
        public string Addres { get; set; }
        public long Mobile_1 { get; set; }
        public Nullable<long> Mobile_2 { get; set; }
        public string Photo_path { get; set; }
        public string Refer_By { get; set; }
        public Nullable<long> Refer_Mobile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Enroll_Cust> tbl_Enroll_Cust { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_LiftedCustomer> tbl_LiftedCustomer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_MonthlyPayment> tbl_MonthlyPayment { get; set; }
    }
}
