//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RNM_CHITFUND.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_MonthlyPayment
    {
        public int Enroll_ID { get; set; }
        public string Cust_ID { get; set; }
        public string Chitt_ID { get; set; }
        public Nullable<decimal> Recieved_Amt { get; set; }
        public decimal Due_Amt { get; set; }
        public Nullable<System.DateTime> Recieved_Date { get; set; }
        public string ModeOfPayment { get; set; }
        public string MonthOfPament { get; set; }
    
        public virtual tbl_Chitti tbl_Chitti { get; set; }
        public virtual tbl_Cust tbl_Cust { get; set; }
        public virtual tbl_Enroll_Cust tbl_Enroll_Cust { get; set; }
    }
}
